import {
  Baby,
  BookOpen,
  Camera,
  Clapperboard,
  Coffee,
  Cpu,
  Droplets,
  Dumbbell,
  Gamepad2,
  Gem,
  GraduationCap,
  Heart,
  House,
  Leaf,
  Mic,
  Music,
  Palette,
  PawPrint,
  Plane,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sun,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

/** Category `icon` values (lucide kebab-case names) → components. */
const CATEGORY_ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  shirt: Shirt,
  dumbbell: Dumbbell,
  sun: Sun,
  utensils: Utensils,
  plane: Plane,
  cpu: Cpu,
  'gamepad-2': Gamepad2,
  gamepad: Gamepad2,
  baby: Baby,
  'graduation-cap': GraduationCap,
  droplets: Droplets,
  heart: Heart,
  smartphone: Smartphone,
  camera: Camera,
  wallet: Wallet,
  house: House,
  home: House,
  leaf: Leaf,
  gem: Gem,
  palette: Palette,
  music: Music,
  mic: Mic,
  coffee: Coffee,
  'book-open': BookOpen,
  'paw-print': PawPrint,
  'shopping-bag': ShoppingBag,
  clapperboard: Clapperboard,
}

export function categoryIcon(name?: string | null): LucideIcon {
  return (name && CATEGORY_ICONS[name.trim().toLowerCase()]) || Sparkles
}
